name: Secret Scan

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@2cddfaf8591b41cb6b9b9906e47760ed657f0a48
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
